/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MGPLStandaloneSetup extends MGPLStandaloneSetupGenerated {

	def static void doSetup() {
		new MGPLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
